-- init_db.sql — Команды для инициализации БД системы нарядов VITECHBOT
-- Попарное голосование 2/1/0 (Курс, ГБР, Столовая, ЗУБ + объекты столовой)

-- ============================================
-- 1. Инициализация через Python (РЕКОМЕНДУЕТСЯ)
-- ============================================
--   python setup_db.py
-- или:
--   python -c "from database import init_db, init_survey_objects; init_db(); init_survey_objects()"
--
-- Создаёт таблицы и объекты для опроса (Курс, ГБР, Столовая, ЗУБ; ГЦ, овощи, тарелки, железо, стаканы, лента).

-- ============================================
-- 2. Если duty_objects содержит старые данные
-- ============================================
--
-- Очистить и пересоздать объекты:
--   DELETE FROM duty_objects;
--   DELETE FROM sqlite_sequence WHERE name='duty_objects';
-- Затем выполните setup_db.py или init_survey_objects().
--
-- Вручную (если нужно):
-- INSERT INTO duty_objects (name, parent_id) 
--   SELECT 'Горячий цех', id FROM duty_objects WHERE name='Столовая' AND parent_id IS NULL;
-- INSERT INTO duty_objects (name, parent_id) 
--   SELECT 'Овощной цех', id FROM duty_objects WHERE name='Столовая' AND parent_id IS NULL;
-- INSERT INTO duty_objects (name, parent_id) 
--   SELECT 'Тарелки', id FROM duty_objects WHERE name='Столовая' AND parent_id IS NULL;
-- INSERT INTO duty_objects (name, parent_id) 
--   SELECT 'Железо', id FROM duty_objects WHERE name='Столовая' AND parent_id IS NULL;
-- INSERT INTO duty_objects (name, parent_id) 
--   SELECT 'Стаканы', id FROM duty_objects WHERE name='Столовая' AND parent_id IS NULL;
-- INSERT INTO duty_objects (name, parent_id) 
--   SELECT 'Лента', id FROM duty_objects WHERE name='Столовая' AND parent_id IS NULL;

-- ============================================
-- 3. Роли пользователей
-- ============================================
-- Назначить админа (замените TELEGRAM_ID на ваш):
-- UPDATE users SET role = 'admin' WHERE telegram_id = 1027070834;
--
-- Назначить сержанта:
-- UPDATE users SET role = 'sergeant' WHERE telegram_id = TELEGRAM_ID;
--
-- Назначить помощника (один на группу):
-- UPDATE users SET role = 'assistant' WHERE telegram_id = TELEGRAM_ID;

-- ============================================
-- 4. Таблица duties (если используется вместо duty_schedule)
-- ============================================
-- CREATE TABLE IF NOT EXISTS duties (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   user_id INTEGER NOT NULL,
--   date TEXT NOT NULL,
--   role TEXT NOT NULL,
--   object_type TEXT,
--   FOREIGN KEY (user_id) REFERENCES users (id)
-- );
