services:
  - type: worker
    name: course-bot
    runtime: python
    branch: main
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: 8500147929:AAFGg3Fp1wV34np6VRGlO-x8cdEqhtF-tZ0
      - key: ADMIN_ID
        value: 1027070834
      - key: DATABASE
        value: bot.db
      - key: UPLOAD_FOLDER
        value: uploads
